# Copyright RacingSim. All Rights Reserved.
#
# TRACK-002: runs Author-PrototypeGrayboxLevel.py inside the Unreal editor to (re)author
# Content/Tracks/Prototype/Maps/L_Meridian_Graybox.umap.
#
# WHY THIS INVOCATION FORM, AND NOT `-run=pythonscript`:
#
#   Docs/Environment.md records that this project's ONE proven headless editor command is
#
#       UnrealEditor-Cmd.exe <uproject> -ExecCmds="..." -unattended -nopause -nosplash
#           -nullrhi -stdout -utf8output
#
#   which starts the EDITOR (GIsEditor true, IsRunningCommandlet() false), not a
#   commandlet. TRACK-001's spec header quotes the engine source establishing that
#   distinction for automation-test collection; the same distinction matters here,
#   because EditorLoadingAndSavingUtils/EditorActorSubsystem are editor-subsystem APIs.
#   Reusing the proven form removes a whole class of "does the commandlet host have a
#   world" failure from a content-authoring step that touches a binary asset.
#
# The script is idempotent: it builds the map from scratch every run and overwrites.
#
# EXIT CODE IS NOT EVIDENCE. As with the automation gate, the editor's exit code is not
# trustworthy here; this wrapper greps the captured stdout for the script's own
# AUTHORING_OK marker and for the saved package path.

param(
    [string]$ProjectPath = (Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'RacingSim.uproject'),
    [string]$OutFile
)

$ErrorActionPreference = 'Continue'

$Cmd = 'C:\Program Files\Epic Games\UE_5.8\Engine\Binaries\Win64\UnrealEditor-Cmd.exe'
$Script = Join-Path $PSScriptRoot 'Author-PrototypeGrayboxLevel.py'

if (-not $OutFile) {
    $OutFile = Join-Path (Split-Path -Parent $ProjectPath) 'Saved\TRACK002\author-graybox-level.log'
}
$OutDir = Split-Path -Parent $OutFile
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }

# THE SCRIPT PATH MUST NOT CONTAIN A SPACE, AND THIS ONE DOES.
#
# Found by running, not by reading. `-ExecCmds="py \"<path with spaces>\"; Quit"` does not
# work: the engine's ExecCmds tokenizer splits the command on whitespace and hands Python
# only the first token, so `py "C:\Users\jun yi\...\Author-PrototypeGrayboxLevel.py"`
# arrives as the bare string `C:\Users\jun`. That does not end in `.py`, so
# FPythonScriptPlugin::ExecPythonCommandEx's TryExtractPathnameAndCommand declines to
# treat it as a file and evaluates it as literal Python instead, producing
#
#   LogPython: Error: SyntaxError: unexpected character after line continuation
#              character (<string>, line 1)
#   LogPython: Error:   C:\Users\jun
#
# -- a message that names neither the real cause nor this script. Note that the engine's
# own comment at PythonScriptPlugin.cpp:1813-1822 advertises support for pathnames with
# spaces; that support is real, but it is downstream of the ExecCmds split, so it never
# sees the whole path.
#
# Every path on this machine contains a space (`jun yi`, `central-command\racing` is fine
# but the home directory is not), so this is not avoidable by moving the file. The 8.3
# short path is the fix: it is the same file, generated by the filesystem, and needs no
# copy that could drift from the reviewed source.
#
# AND THE SHORT PATH MUST BE TAKEN OF THE DIRECTORY ONLY, NOT OF THE FILE.
#
# Also found by running. Short-pathing the whole file yields `...\AUTHOR~1.PY` -- and 8.3
# names are UPPERCASE. FPythonScriptPlugin::ExecPythonCommandEx decides whether its
# argument is a file or a snippet of literal Python with
#
#     UE::String::FindFirst(InOutPythonCommand.Command, TEXT(".py"))
#
# and UE::String::FindFirst defaults to ESearchCase::CaseSensitive (Core/String/Find.h:23).
# `.PY` therefore does not match `.py`, the path is evaluated as source code, and the
# backslashes make it a line-continuation syntax error:
#
#   LogPython: Error: SyntaxError: unexpected character after line continuation
#              character (<string>, line 1)
#   LogPython: Error:   C:\Users\JUNYI~1\DOCUME~1\...\AUTHOR~1.PY
#
# Same misleading message as the space bug, entirely different cause, and the second one
# only becomes visible once the first is fixed.
#
# Short-pathing the PARENT DIRECTORY and re-joining the real filename gives a path with
# no spaces AND a lowercase extension, which satisfies both constraints at once.
$Fso = New-Object -ComObject Scripting.FileSystemObject
$ShortDir = $Fso.GetFolder((Split-Path -Parent $Script)).ShortPath
$ShortScript = Join-Path $ShortDir (Split-Path -Leaf $Script)

if ([string]::IsNullOrWhiteSpace($ShortScript) -or $ShortScript -match ' ') {
    # 8.3 name generation can be disabled per-volume. Fall back to a copy in a
    # space-free directory rather than failing, but say so, because the executed bytes
    # are then a copy rather than the reviewed file.
    $Fallback = Join-Path $env:TEMP 'RacingSimTrack002\author_graybox_level.py'
    $FallbackDir = Split-Path -Parent $Fallback
    if (-not (Test-Path $FallbackDir)) { New-Item -ItemType Directory -Path $FallbackDir -Force | Out-Null }
    Copy-Item -LiteralPath $Script -Destination $Fallback -Force
    if ($Fallback -match ' ') {
        Write-Output "NO_SPACE_FREE_PATH -- cannot invoke the authoring script; aborting."
        exit 1
    }
    Write-Output "SHORT_PATH_UNAVAILABLE -- executing a copy at $Fallback"
    $ShortScript = $Fallback
}

Write-Output "PROJECT=$ProjectPath"
Write-Output "SCRIPT=$Script"
Write-Output "SCRIPT_INVOKED_AS=$ShortScript"

& $Cmd $ProjectPath `
    -ExecCmds="py $ShortScript" `
    -unattended -nopause -nosplash -nullrhi -stdout -utf8output *>&1 |
    Tee-Object -FilePath $OutFile | Out-Null

Write-Output "PROCESS_EXITCODE=$LASTEXITCODE"

# EVIDENCE COMES FROM THE ENGINE LOG, NOT FROM STDOUT.
#
# Third thing found by running. `unreal.log()` emits at LOG verbosity (the lines read
# `LogPython: [TRACK-002] ...` with no verbosity token, unlike the engine's own
# `LogPython: Display: ...`), and `-stdout` forwards Display and above only. So the
# authoring script's entire report -- track length, gate count, gate distances, the
# SAVED and AUTHORING_OK markers -- reaches Saved/Logs/RacingSim.log and NEVER reaches
# the captured stdout.
#
# The first version of this wrapper read stdout alone and therefore printed
# "NO_AUTHORING_OK -- the map was not authored" for a run that had authored the map
# perfectly. A checker that reports failure on success is as dangerous as one that
# reports success on failure, and this one would have been believed.
#
# Both sources are scanned: stdout for engine-level errors, the engine log for the
# script's own report.
$Text = @(Get-Content -LiteralPath $OutFile)

$EngineLog = Join-Path (Split-Path -Parent $ProjectPath) 'Saved\Logs\RacingSim.log'
if (Test-Path $EngineLog) {
    Write-Output "ENGINE_LOG=$EngineLog"
    $Text += @(Get-Content -LiteralPath $EngineLog)
} else {
    Write-Output "ENGINE_LOG_MISSING=$EngineLog -- the script's own report cannot be read."
}

$Ok = @($Text | Select-String -Pattern 'AUTHORING_OK' -SimpleMatch)
$Saved = @($Text | Select-String -Pattern 'SAVED /Game/' -SimpleMatch)
$Errors = @($Text | Select-String -Pattern 'TRACK-002\] FAILED|LogPython: Error|Error: ' )

Write-Output "AUTHORING_OK_MATCHES=$($Ok.Count)"
Write-Output "SAVED_MATCHES=$($Saved.Count)"
foreach ($Line in $Saved) { Write-Output "  $Line" }

Write-Output "--- TRACK-002 script output ---"
foreach ($Line in @($Text | Select-String -Pattern '\[TRACK-002\]')) { Write-Output "  $Line" }

Write-Output "ERROR_MATCHES=$($Errors.Count)"
foreach ($Line in $Errors) { Write-Output "  ERR: $Line" }

if ($Ok.Count -lt 1) {
    Write-Output 'NO_AUTHORING_OK -- the map was not authored; treat as a failure regardless of exit code.'
    exit 1
}

exit 0
